# Generated by Django 6.0.2 on 2026-02-07 07:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('github_connected', models.BooleanField(default=False)),
                ('jira_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_id', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('cloud_id', models.CharField(max_length=100)),
                ('is_tracked', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jira_projects',
                'unique_together': {('user', 'jira_id', 'cloud_id')},
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('github_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('is_private', models.BooleanField(default=False)),
                ('is_tracked', models.BooleanField(default=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repositories',
                'unique_together': {('user', 'github_id')},
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha', models.CharField(max_length=40)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('committed_at', models.DateTimeField()),
                ('url', models.URLField()),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('extracted_ticket_keys', models.JSONField(default=list)),
                ('is_unlinked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core.repository')),
            ],
            options={
                'db_table': 'commits',
                'ordering': ['-committed_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_id', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=100)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('reporter', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('created_at_jira', models.DateTimeField()),
                ('updated_at_jira', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.jiraproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
                'unique_together': {('user', 'jira_id')},
            },
        ),
        migrations.CreateModel(
            name='HygieneAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('commit_no_ticket', 'Commit without Jira ticket'), ('status_no_commit', 'Status change without commits'), ('time_no_code', 'Time logged without code'), ('stalled_ticket', 'Ticket worked on but never moved'), ('high_effort_low_output', 'High effort, low output')], max_length=50)),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('detected_for_start', models.DateField()),
                ('detected_for_end', models.DateField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.commit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hygiene_alerts', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
            ],
            options={
                'db_table': 'hygiene_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='core.ticket'),
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('status_change', 'Status Change'), ('comment', 'Comment'), ('field_change', 'Field Change')], max_length=50)),
                ('author', models.CharField(max_length=255)),
                ('from_status', models.CharField(blank=True, max_length=100, null=True)),
                ('to_status', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_body', models.TextField(blank=True, null=True)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_value', models.TextField(blank=True, null=True)),
                ('to_value', models.TextField(blank=True, null=True)),
                ('activity_at', models.DateTimeField()),
                ('jira_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_activities',
                'ordering': ['-activity_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('jira', 'Jira')], max_length=20)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('cloud_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_tokens',
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='commit',
            unique_together={('user', 'repository', 'sha')},
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_tickets', models.IntegerField(default=0)),
                ('total_commits', models.IntegerField(default=0)),
                ('tickets_completed', models.IntegerField(default=0)),
                ('total_time_logged_seconds', models.IntegerField(default=0)),
                ('unlinked_commits', models.IntegerField(default=0)),
                ('non_code_activities', models.IntegerField(default=0)),
                ('summary_text', models.TextField()),
                ('markdown_report', models.TextField()),
                ('report_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_reports',
                'ordering': ['-start_date'],
                'unique_together': {('user', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_id', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=255)),
                ('time_spent_seconds', models.IntegerField()),
                ('time_spent_display', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='core.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'worklogs',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'jira_id')},
            },
        ),
    ]
